force-app/main/objects/Analytics_Trial_Task__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Actionable_Link__c</fullName>
        <label>Actionable Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is_Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subtitle__c</fullName>
        <label>Subtitle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Order__c</fullName>
        <label>Task Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task_Title__c</fullName>
        <label>Task Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Analytics Trial Task</label>
</CustomObject>

force-app/main/classes/MyCustomTaskController.cls
public class MyCustomTaskController {

    @AuraEnabled public List<Analytics_Trial_Task__c> taskList {get; set;}

    @AuraEnabled
    public static MyCustomTaskController queryRecords () {
	
		MyCustomTaskController controller = new MyCustomTaskController();
        
        controller.taskList = [
            SELECT Id, Name, Task_Title__c, Task_Order__c, Is_Completed__c, Completed_Date__c, Actionable_Link__c, Subtitle__c 
            FROM Analytics_Trial_Task__c
            ORDER BY Task_Order__c ASC
        ]; 
        
        return controller;
    }
    
    @AuraEnabled 
    public static String toggleStatus (Id taskId, Boolean status) {
        
        Analytics_Trial_Task__c att = [
            SELECT Id, Is_Completed__c, Completed_Date__c 
            FROM Analytics_Trial_Task__c 
            WHERE Id =: taskId
        ];
        
        att.Is_Completed__c = status;
        
        if (status == TRUE) {
            att.Completed_Date__c = Date.Today();
        } else {
            att.Completed_Date__c = NULL;
        }
        
        try {
	        update att;      
            return 'Success';
        } catch (Exception e) {
            return e.getMessage();
        } 


        
    }

}