force-app/main/objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Building_Code__c</fullName>
        <label>Building Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Maximum_Number_of_Flats__c</fullName>
        <label>Maximum Number of Flats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/Flat__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <description>This field stores the building of the flat.</description>
        <inlineHelpText>This field stores the building of the flat.</inlineHelpText>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Flats</relationshipLabel>
        <relationshipName>Flats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Vacant</fullName>
                    <default>true</default>
                    <label>Vacant</label>
                </value>
                <value>
                    <fullName>Occupied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Flat</label>
    <nameField>
        <label>Flat Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Lease_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Lease Contracts</relationshipLabel>
        <relationshipName>Lease_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Flat</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Please enter a vacant flat within the selected building.</errorMessage>
            <filterItems>
                <field>Flat__c.Building__c</field>
                <operation>equals</operation>
                <valueField>$Source.Building__c</valueField>
            </filterItems>
            <filterItems>
                <field>Flat__c.Status__c</field>
                <operation>equals</operation>
                <value>Vacant</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Flat__c</referenceTo>
        <relationshipLabel>Lease Contracts</relationshipLabel>
        <relationshipName>Lease_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved by Coordinator&apos;s Manager</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Rejected by Coordinator&apos;s Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tenant_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Tenant Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Contacts with Record type &quot;Tenant&quot; can be used.</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Tenant</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Lease Contracts</relationshipLabel>
        <relationshipName>Lease_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Lease Contract</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Lease Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/classes/ContractSearchControllerTest.cls
@isTest
public with sharing class ContractSearchControllerTest {
    
    @testSetup
    public static void setup(){
        String tName = 'Penny';
        Building__c testBuilding = new Building__c(Name = 'ABC Test Heights', Maximum_Number_of_Flats__c = 50, Building_Code__c='ABC');
        insert testBuilding;
        Flat__c testFlat = new Flat__c(Name = '12', Building__c = testBuilding.id, Status__c = 'Vacant');
        insert testFlat;
        Id contactRecordType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Tenant').getRecordTypeId();
        Contact testTenant = new Contact(FirstName = 'Diksha',LastName = 'Mehta', Email = 'diksha@fs.com');
        testTenant.RecordTypeId = contactRecordType;
        insert testTenant;
        Lease_Contract__c testContract = new Lease_Contract__c(Tenant_Contact__c = testTenant.ID, Building__c = testBuilding.ID, Flat__c = testFlat.ID);
        insert testContract;
    }
    @isTest
    public static void testContractSearchByTenant(){
        
        Test.startTest();
        List<Lease_Contract__c> contractListForTest = ContractSearchController.searchByTenant('Mehta');
        Test.stopTest();   
        
        System.assertEquals('Diksha Mehta', contractListForTest[0].Tenant_Contact__r.Name);
        
    }
    @isTest
    public static void testContractSearchByBuilding(){
        
        Test.startTest();
        List<Lease_Contract__c> buildingListForTest = ContractSearchController.searchByBuilding('ABC');
        Test.stopTest();   
        
        System.assertEquals('ABC Test Heights', buildingListForTest[0].Building__r.Name);
        
    }
}