force-app/main/objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Building_Code__c</fullName>
        <label>Building Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/Flat__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <description>This field stores the building of the flat.</description>
        <inlineHelpText>This field stores the building of the flat.</inlineHelpText>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Flats</relationshipLabel>
        <relationshipName>Flats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Flat</label>
    <nameField>
        <label>Flat Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Lease_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Lease Contracts</relationshipLabel>
        <relationshipName>Lease_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Flat</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Please enter a vacant flat within the selected building.</errorMessage>
            <filterItems>
                <field>Flat__c.Building__c</field>
                <operation>equals</operation>
                <valueField>$Source.Building__c</valueField>
            </filterItems>
            <filterItems>
                <field>Flat__c.Status__c</field>
                <operation>equals</operation>
                <value>Vacant</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Flat__c</referenceTo>
        <relationshipLabel>Lease Contracts</relationshipLabel>
        <relationshipName>Lease_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tenant_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Tenant Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Contacts with Record type &quot;Tenant&quot; can be used.</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Tenant</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Lease Contracts</relationshipLabel>
        <relationshipName>Lease_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Lease Contract</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Lease Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/classes/LeaseContractPathComponentControllerTest.cls
@isTest
public class LeaseContractPathComponentControllerTest {

    @isTest
    public static void testMethod1(){
        
        Test.startTest();
        Account a = new Account();
        a.Name = 'Test';
        insert a;
        
        Contact c = new Contact();
        c.Firstname = 'Test1';
        c.LastName = 'Test2';
        c.RecordTypeId = '0122w000000J7IKAA0';
        c.AccountId = a.Id;
        insert c;
        
        Building__c b = new Building__c();
        b.Building_Code__c = 'BT';
        b.Name = 'test';
        insert b;
        
        Flat__c f = new Flat__c();
        f.Name = 'testFlat';
        f.Building__c = b.Id;
        insert f;
        
        Lease_Contract__c lc = new Lease_Contract__c();
        lc.Building__c = b.Id;
        lc.Flat__c = f.Id;
        lc.Tenant_Contact__c = c.Id;
        insert lc;
       
        System.assertEquals(null, LeaseContractPathComponentController.getStage(lc.Id));
        Test.stopTest();
    }
}