force-app/main/objects/Building__c.object
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/Flat__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <description>This field stores the building of the flat.</description>
        <inlineHelpText>This field stores the building of the flat.</inlineHelpText>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Flats</relationshipLabel>
        <relationshipName>Flats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Vacant</fullName>
                    <default>true</default>
                    <label>Vacant</label>
                </value>
                <value>
                    <fullName>Occupied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Flat</label>
    <nameField>
        <label>Flat Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Lease_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Lease Contracts</relationshipLabel>
        <relationshipName>Lease_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This field refers to the expiration date of the Contract.</description>
        <inlineHelpText>This field refers to the expiration date of the Contract.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Flat</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Please enter a vacant flat within the selected building.</errorMessage>
            <filterItems>
                <field>Flat__c.Building__c</field>
                <operation>equals</operation>
                <valueField>$Source.Building__c</valueField>
            </filterItems>
            <filterItems>
                <field>Flat__c.Status__c</field>
                <operation>equals</operation>
                <value>Vacant</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Flat__c</referenceTo>
        <relationshipLabel>Lease Contracts</relationshipLabel>
        <relationshipName>Lease_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <description>Revenue generated by the corresponding tenant.</description>
        <inlineHelpText>Revenue generated by the corresponding tenant.</inlineHelpText>
        <label>Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>This field refers to the starting date of the Contract.</description>
        <inlineHelpText>This field refers to the starting date of the Contract.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved by Coordinator&apos;s Manager</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Rejected by Coordinator&apos;s Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tenant_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Tenant Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Contacts with Record type &quot;Tenant&quot; can be used.</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Tenant</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Lease Contracts</relationshipLabel>
        <relationshipName>Lease_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Lease Contract</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Lease Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/classes/LeaseContractDataUtil.cls
public class LeaseContractDataUtil {
    
   /* public static void createLeaseContract(Date startDate){
        
        List<Contact> conList = [Select Id, Name, FirstName, LastName, AccountId from Contact where RecordTypeId = '0122w000000J7IKAA0'];
        List<Id> accountIdList = new List<Id>();
        for(Contact con: conList){
            accountIdList.add(con.AccountId);
        }
        List<Account> acList = [Select Id, Name from Account where Id in :accountIdList];
        List<Building__c> buildingList = [Select Id, Name from Building__c];
        List<Id> buildingIdList = new List<Id>();
        for(Building__c b: buildingList){
            buildingIdList.add(b.Id);
        }
        Map<Id, Id> flatBuildingMap = new Map<Id, Id>();
        List<Flat__c> flatList = [Select Id, Name, building__c from Flat__c where building__c in :buildingIdList];
        for(Flat__c f:flatList){
            flatBuildingMap.put(f.Id, f.building__c);
        }
        List<Lease_Contract__c> lcList = new List<Lease_Contract__c>();
        
        Integer buildingListSize = buildingList.size() - 1;
        Integer flatListSize = flatList.size() - 1;
        Set<Integer> usedNumberSet = new Set<Integer>();
        //startDate = Date.newInstance(200, 06, 26);
        for(Contact con:conList){
            Integer randomNumberFirst = Integer.valueof((Math.random() * 9));
            Integer randomNumberSecond = Integer.valueof((Math.random() * flatListSize));
            Lease_Contract__c lc = new Lease_Contract__c();
            lc.start_Date__c = startDate.addDays(randomNumberSecond);
            lc.Revenue__c = randomNumberFirst * 1000;
            lc.end_Date__c = startDate.addDays(randomNumberFirst * 90);
            lc.Tenant_Contact__c = con.Id;
            lc.Status__c = 'Approved';
            if(!usedNumberSet.contains(randomNumberSecond) && usedNumberSet.size() < buildingList.size()){
                 lc.Flat__c = flatList[randomNumberSecond].Id;
                if(flatBuildingMap != null && flatBuildingMap.containsKey(lc.Flat__c)){
                    usedNumberSet.add(randomNumberSecond);
                    lc.Building__c = flatBuildingMap.get(lc.Flat__c);
                    flatList.remove(randomNumberSecond);
                    flatListSize = flatListSize - 1;
                    lcList.add(lc);
                }
                
            }
            
        }
        System.debug('usedNumberSet = '  + usedNumberSet.size());
        if(lcList.size() > 0){
            upsert lcList;
        }
    }
    
    public static void updatedLeaseContract(){
        List<Lease_Contract__c> lcList = [Select Id, Revenue__c, end_date__c from Lease_Contract__c];
        
        for(Lease_Contract__c lc:lcList){
            //Integer randomNumberFirst = Integer.valueof((Math.random() * lcList.size()));
            //lc.Revenue__c = randomNumberFirst * 100;
            //lc.End_Date__c = lc.End_Date__c.addDays(randomNumberFirst);        
            lc.Status__c = 'Approved';    
        }
        update lcList;
        
    }
    
    public static void createTenantContacts(){
        List<String> firstNameList = new List<String>{'Michael','Angela','Bruce','Edward','Anna', 'Steve', 'Mark', 'Veronica', 'Bella'};
            List<String> lastNameList = new List<String>{'Connor','Hills','Bill','Gates','Clinton', 'Grey', 'Jobs', 'Klayton'};
                
                List<Account> acList = new List<Account>();
        for(Integer i = 0; i <100; i++){
            Integer firstlistSize = firstNameList.size() - 1;
            Integer secondlistSize = lastNameList.size() - 1;
            Integer randomNumberFirst = Integer.valueof((Math.random() * firstlistSize));
            Integer randomNumberSecond = Integer.valueof((Math.random() * secondlistSize));
            String randomFirsString= firstNameList[randomNumberFirst];
            String randomSecondString= lastNameList[randomNumberSecond];
            System.debug('randomString is'+randomFirsString + ' ' + randomSecondString);
            Account ac = new Account();
            ac.Name = randomFirsString + ' ' + randomSecondString;
            //ac.FirstName = randomFirsString;
            //ac.LastName = randomNumberSecond;
            acList.add(ac);
        }
        System.debug('acList = ' + acList.size());
        insert acList;
        
        
        acList = [Select Id, Name from Account limit 100];
        List<Contact> conList = new List<Contact>();
        System.debug(acList.size());
        for(Account ac:acList){
            String name = ac.Name;
            Contact con = new Contact();
            con.AccountId = ac.Id;
            
            con.RecordTypeId = Id.valueOf('0122w000000J7IKAA0');
            //con.Name = ac.Name;
            if(name.subStringAfter(' ') != null){
                con.FirstName= name.subStringBefore(' ');
                con.LastName = name.subStringAfter(' ');
                conList.add(con);
            }
        }
        insert conList;
        
    }*/
    
}