force-app/main/objects/Building__c.object
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/Flat__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <description>This field stores the building of the flat.</description>
        <inlineHelpText>This field stores the building of the flat.</inlineHelpText>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Flats</relationshipLabel>
        <relationshipName>Flats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Vacant</fullName>
                    <default>true</default>
                    <label>Vacant</label>
                </value>
                <value>
                    <fullName>Occupied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Flat</label>
    <nameField>
        <label>Flat Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Lease_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Lease Contracts</relationshipLabel>
        <relationshipName>Lease_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Term__c</fullName>
        <description>This field represents the number of days in the contract.</description>
        <formula>End_Date__c - Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field represents the number of days in the contract.</inlineHelpText>
        <label>Contract Term(Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days_Remaining_In_Contract__c</fullName>
        <description>This field returns the number of days remaining in the Lease Contract.</description>
        <formula>IF(End_Date__c - TODAY()&gt;0,End_Date__c - TODAY() ,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field returns the number of days remaining in the Lease Contract.</inlineHelpText>
        <label>Days Remaining In Contract</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Flat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Flat</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Please enter a vacant flat within the selected building.</errorMessage>
            <filterItems>
                <field>Flat__c.Building__c</field>
                <operation>equals</operation>
                <valueField>$Source.Building__c</valueField>
            </filterItems>
            <filterItems>
                <field>Flat__c.Status__c</field>
                <operation>equals</operation>
                <value>Vacant</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Flat__c</referenceTo>
        <relationshipLabel>Lease Contracts</relationshipLabel>
        <relationshipName>Lease_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved by Coordinator&apos;s Manager</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Rejected by Coordinator&apos;s Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tenant_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Tenant Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Contacts with Record type &quot;Tenant&quot; can be used.</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Tenant</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Lease Contracts</relationshipLabel>
        <relationshipName>Lease_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Lease Contract</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Lease Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/classes/ContractSearchController.cls
public class ContractSearchController {
    @AuraEnabled
    public static List<Lease_Contract__c> searchByTenant(String tenantName){
        String tName = '%' + tenantName + '%';
        List<Lease_Contract__c> contractListByTenant = [select id, Name, Tenant_Contact__r.Name, Flat__r.Name, Status__c,
                                                        Building__r.Name,Contract_Term__c, Days_Remaining_In_Contract__c
                                                        from Lease_Contract__c
                                                        where Tenant_Contact__r.Name like :tName];
        System.debug(contractListByTenant);
        return contractListByTenant;
    }
    @AuraEnabled
    public static List<Lease_Contract__c> searchByBuilding(String buildingName){
        String bName = '%' + buildingName + '%';
        List<Lease_Contract__c> contractListByTenant = [select id, Name, Tenant_Contact__r.Name, Flat__r.Name, Status__c,
                                                        Building__r.Name,Contract_Term__c, Days_Remaining_In_Contract__c
                                                        from Lease_Contract__c
                                                        where Building__r.Name like :bName];
        System.debug(contractListByTenant);
        return contractListByTenant;
        
    }

}