force-app/main/objects/OpportunityHistory__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CloseDate__c</fullName>
        <label>CloseDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExpectedRevenue__c</fullName>
        <label>Expected Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ForecastCategory__c</fullName>
        <label>To ForecastCategory</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Omitted</fullName>
                </value>
                <value>
                    <fullName>Pipeline</fullName>
                </value>
                <value>
                    <fullName>BestCase</fullName>
                </value>
                <value>
                    <fullName>Forecast</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity ID</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Histories</relationshipLabel>
        <relationshipName>Opportunity_Histories</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <label>Probability</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>StageName__c</fullName>
        <label>Stage Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospecting</fullName>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Needs Analysis</fullName>
                </value>
                <value>
                    <fullName>Value Proposition</fullName>
                </value>
                <value>
                    <fullName>Id. Decision Makers</fullName>
                </value>
                <value>
                    <fullName>Perception Analysis</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote</fullName>
                </value>
                <value>
                    <fullName>Negotiation/Review</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity History</label>
    <nameField>
        <label>Opportunity History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/classes/DataManager_CleanUp.cls
// Clean up the Org from Opps and linked objects (i.e. OppHistory__c and OppLineItem)
public class DataManager_CleanUp implements Queueable  {
    private map<string, map<string,id>> objectIdbyName;
    
    // List of Accs to edit, initiated in the constructor
    private List<Account> DTC_Accs;
    
    
    public DataManager_CleanUp() {
        // Init Object IDs map
        objectIdbyName = DataManager_Utils.getObjectIdbyName();
        
        // Init Accounts list
        DTC_Accs = createAccs(DataManager_Utils.getCsv('DTC_Account'));
    }
    
	public void execute(QueueableContext context) {
        // Delete old Tasks
        Task[] tasks = [SELECT Id FROM Task];
        if (tasks.size() > 0) {
            System.debug('Deleting Tasks');
            delete tasks;
        }
        
        // Delete old Events
        Event[] events = [SELECT Id FROM Event];
        if (events.size() > 0) {
            System.debug('Deleting Events');
            delete events;
        }
        
        // Delete old OppsHistories
        OpportunityHistory__c[] oppHists = [SELECT Amount__c,CloseDate__c,CreatedDate,ExpectedRevenue__c,ForecastCategory__c,Id,Name,OpportunityId__c,Probability__c,StageName__c FROM OpportunityHistory__c];
        if (oppHists.size() > 0) {
            System.debug('Deleting OppHists');
            delete oppHists;
        }
        
        // Delete Opps
        Opportunity[] opps = [select Account.Name,Amount,CreatedDate,CloseDate,LeadSource,Name,Owner.Name,StageName,Type from Opportunity];
        if (opps.size() > 0) {
            System.debug('Deleting Opps');
            delete opps;  
        } 
        
        //Delete Cases
        Case[] serviceCases = [select Id from Case];
        if(serviceCases.size() > 0){
            System.debug('Deleting Cases');
            delete serviceCases;
        }
        
        // Delete Accounts
        Account[] accs = [select Id from Account];
        if (accs.size() > 0) {
            System.debug('Deleting Accs');
            delete accs;  
        }
        
        insert DTC_Accs;
        
        // ==============================================
        // 					NEXT JOB!
        // ==============================================
        
        if(!test.isRunningTest()) {
            // 1 - Add Accounts and Opps
            System.enqueueJob(new DataManager_Opportunity());
        }
    }
    
    // =========================================================================
    //           Account Record Creation
    // =========================================================================
	
    public List<Account> createAccs(String[] filelines) {
        List<Account> Accs = new List<Account>();
        for (Integer i=1;i<filelines.size();i++)
        {
            String[] inputvalues = filelines[i].split(',');
            
            // Replace classic Admin User by the actual admin name!
            String userName = inputValues[5];
            if (userName == 'Admin User') {
                userName = UserInfo.getName();
            }
            
            Account temp = new Account();
            temp.Industry = inputValues[0];
            temp.Name = inputValues[1];
            temp.AccountSource = inputValues[2];
            temp.BillingCountry = inputValues[3];
            temp.BillingState = inputValues[4];
            temp.OwnerId = objectIdbyName.get('User').get(userName);
            temp.Type = inputValues[6];
            temp.AnnualRevenue = decimal.ValueOf(inputValues[7]);
            temp.NumberOfEmployees = integer.ValueOf(inputValues[8]);
            temp.Segment__c = inputValues[9];
            temp.Sic = inputValues[10];
            
            // Add the Account to the list
            Accs.add(temp);
        }
        
        return Accs;
    }
}