force-app/main/objects/US_States__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>USPS_Code__c</fullName>
        <label>USPS Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>US States</label>
</CustomObject>

force-app/main/objects/World_Countries__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Email_Opt_In__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Opt In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>World Countries</label>
</CustomObject>

force-app/main/classes/CountryPicklistController.cls
public class CountryPicklistController {

    @AuraEnabled public List<World_Countries__c> worldCountries {get; set;}
    @AuraEnabled public List<US_States__c> usStates {get; set;}

    @AuraEnabled
    public static CountryPicklistController getListData () {
        
        CountryPicklistController geoPicklistValues = new CountryPicklistController();
        
        geoPicklistValues.worldCountries = [
            SELECT ISO_Code__c, Name, Email_Opt_In__c 
            FROM World_Countries__c
            ORDER BY Name ASC
        ];
        
        geoPicklistValues.usStates = [
            SELECT USPS_Code__c, Name 
            FROM US_States__c
            ORDER BY Name ASC
        ];
        
        return geoPicklistValues;
    }

    
}